const toast=(m)=>{const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const files=document.getElementById("files"), count=document.getElementById("fileCount"), progress=document.getElementById("progress"), pct=document.getElementById("pct"), grid=document.getElementById("skinGrid"), detected=document.getElementById("detected");
const skins=[
["Granger","Night Owl","🌌"],["Hanzo","Soulfire Netherflame","🔥"],["Ling","Dragon Tamer","🪽"],["Kimmy","Frost Wing","❄️"],["Aamon","Vessel of Deceit","👁️"],["Benedetta","Soul Vessels","⚔️"],["Atlas","Starlight","🤖"],["Yu Zhong","Exorcist","🐉"],["Alucard","Obsidian Blade","🗡️"]
];
function addSkin(i){let s=skins[i%skins.length],d=document.createElement("article");d.className="skin";d.innerHTML=`<div class="x">×</div><div style="aspect-ratio:1/1.1;display:grid;place-items:center;font-size:45px;background:linear-gradient(135deg,#182844,#4d2861)">${s[2]}</div><div><strong>${s[0]}</strong><em>${s[1]}</em><small>100% match</small></div>`;d.querySelector(".x").onclick=()=>d.remove();grid.appendChild(d)}
files.onchange=()=>{let n=files.files.length;count.textContent=n?`${n} files`:"No file chosen"; if(!n)return; let p=0;grid.innerHTML="";let timer=setInterval(()=>{p+=Math.floor(Math.random()*10)+4;if(p>100)p=100;progress.style.width=p+"%";pct.textContent=p+"%";detected.textContent=`✦ Detected ( ${Math.min(Math.floor(p/4),27)} )`; if(p>=100){clearInterval(timer);for(let i=0;i<Math.min(9,Math.max(3,n*3));i++)addSkin(i);toast("Skin scan complete");}},180)};
document.getElementById("drop").onclick=(e)=>{if(e.target.tagName!=="INPUT"&&e.target.tagName!=="LABEL")files.click()};
document.querySelector(".manual").onclick=()=>{let name=prompt("Enter hero or skin name");if(name){let d=document.createElement("article");d.className="skin";d.innerHTML=`<div style="aspect-ratio:1/1.1;display:grid;place-items:center;font-size:45px;background:linear-gradient(135deg,#182844,#5b296f)">⚔️</div><div><strong>${name}</strong><em>MANUAL</em><small>Added by you</small></div>`;grid.appendChild(d);toast(name+" added")}};
function toggleTheme(){document.documentElement.style.setProperty("--purple",getComputedStyle(document.documentElement).getPropertyValue("--purple").trim()==="#8d73ff"?"#ff6f9b":"#8d73ff");toast("Accent changed")};
